import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { ToastProvider } from "./ui/Components/ToasterProvider";
import Header from "./ui/Components/CartSidebar";
import Footer from "./ui/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dummy Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      > 
         <AuthProvider>
            <ToastProvider>
            <Header />
            <main className="flex-1 pt-25">
              {children}
            </main>
            <Footer />
            </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}                                                 