import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./ui/Components/Footer";
import Header from "./ui/Components/Header";
import { ToastProvider } from "./ui/Components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dummy Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ToastProvider>

          <Header />
          <main className="flex-1 pt-25">
            {children}
          </main>
          <Footer />

        </ToastProvider>

      </body>
    </html>
  );
}